config/routes.rb
Rails.application.routes.draw do

    namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bathrooms, only: [ :index ]
    end
  end

  put 'location_update', to: 'users#update_location', as: 'location_update'

 resources :bathrooms, only: [:new, :create, :show, :index] do
    resources :bookings, only: [:new, :create, :show, :index]
    resources :reviews, only: [:new, :create, :show, :index]
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bathroom.rb
class Bathroom < ApplicationRecord
  include Filterable

  include PgSearch
  pg_search_scope :search_for_index,
    against: [ :price, :handicapped, :style, :toilet_paper, :wipes, :baby, :bidet],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }


  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :bookings
  has_many :reviews

  validates :address, presence: true
  validates :title, presence: true
  validates :plz, presence: true
  validates :city, presence: true
  validates :photo, presence: true
  validates :price, presence: true
  validates :user, presence: :true
  validates :description, presence: true

  geocoded_by :complete_address
  after_validation :geocode

  def complete_address
    address + " " + plz + " " + city
  end

  def self.class_string(b)
    string = "data-tp=#{b.toilet_paper} data-price=#{b.price} data-baby=#{b.baby} data-bidet=#{b.bidet} data-handicapped=#{b.handicapped} data-style=#{b.style}"
    return string
  end

  def average
    sum = []
    return 0 if self.reviews.empty?
    self.reviews.each do |review|
      sum << review.rating
    end

    average = ((sum.sum).fdiv(sum.count))
    # raise
    return average
  end

  # def reviews_show
  #   self.reviews.each do |review|
  #     review.content
  #     review.rating
  #   end

  # end


end

app/controllers/api/v1/bathrooms_controller.rb
class Api::V1::BathroomsController < Api::V1::BaseController
  def index
    @bathrooms = policy_scope(Bathroom)
    @bathrooms = @bathrooms.select do |bathroom|
      test(bathroom)
    end
  end

  def test(bathroom)
    arr = []
    bathroom_params.each do |key, value|
      p key
      par = bathroom.price <= value.to_i if key == "price"
      par = bathroom[key] == (value == "1") if %w(handicapped wipes baby bidet).include? key
      par = bathroom.style == value if key == "style"
      arr << par
    end
    arr.all?
  end

  def bathroom_params
    params.permit(:price, :handicapped, :style, :toilet_paper, :wipes, :baby, :bidet)
  end

end

app/controllers/bathrooms_controller.rb
class BathroomsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @bathroom = Bathroom.new
    authorize @bathroom
    @bathrooms = policy_scope(Bathroom) #.near(current_user.address, 3)
    @bathrooms = @bathrooms.where.not(latitude: nil, longitude: nil)

    if params[:bathroom]

      @bathroom = Bathroom.new(bathroom_params)
      bathroom_params.each do |key, value|

        if key == "price" && value != ""
          @bathrooms = @bathrooms.where('price <= ?', "#{value}")
        end
        if key == "style" && value != "western"
          @bathrooms = @bathrooms.where('style = ?', "#{value}")
        end
        if (%w(handicapped baby bidet wipes).include? key) && value == "1"
          @bathrooms = @bathrooms.where("#{key} = ?", true)
        end
      end
    end

    @user_location = session[:user_coordinates]
    # @bathrooms = @bathrooms.near([@user_location["latitude"],@user_location["longitude"]], 0.5)
    @markers = @bathrooms.map do |bathroom|
      {
        lat: bathroom.latitude,
        lng: bathroom.longitude,
        icon: 'toilet-marker.png',
        draggable: false
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end

  end

  def show
    @bathroom = Bathroom.find(params[:id])
    @markers =
    [{
      lat: @bathroom.latitude,
      lng: @bathroom.longitude,
      icon: '/toilet-marker.png',
      draggable: false
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }]
    @user_location = session[:user_coordinates]

    @owner = @bathroom.user
    @booking = Booking.new
    @booking.user = current_user
    # authorize @booking


    @last_reviews = Review.where("bathroom_id = #{@bathroom.id}").order(id: :desc).limit(3).reverse
    authorize @bathroom
  end

  def new
    @bathroom = Bathroom.new
    authorize @bathroom
  end

  def create
    @bathroom = Bathroom.new(bathroom_params)
    @bathroom.user = current_user
    authorize @bathroom
    if @bathroom.save
      redirect_to bathroom_path(@bathroom)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def bathroom_params
    params.require(:bathroom).permit(:address , :plz, :city, :title, :description, :price, :photo, :photo_cache, :handicapped, :style, :toilet_paper, :wipes, :baby, :bidet, :user_id)
  end

end

app/views/bathrooms/index.html.erb
<div class="wrapper">


  <div class="container">

    <h1 class="text-center">
      Available Bathrooms
    </h1>


<!--
    <div class="filter-bar">
      <form action="">
        <label for="search">search</label>
        <input type="input" id="search" name="search">
        <label for="baby">Baby</label>
        <input type="checkbox" name="baby">
        <label for="handicapped">Handicapped</label>
        <input type="checkbox" name="handicapped">
        <label for="bidet">Bidet</label>
        <input type="checkbox" name="bidet">
        <label for="style">Style:</label>
        <select name="style">
          <option value="all">All</option>
          <option value="western">Western</option>
          <option value="japanese">Japanese</option>
          <option value="turkish">Turkish</option>
        </select>
        <label for="price">Price in cent:</label>
        <input type="number" name="price">
      </form>
    </div>

  -->

  <div class="available-bathrooms">
    <div class="search-grid">
      <div class="filter-form">

        <div class="search-options">
          <h4>Options</h4>
          <%= simple_form_for @bathroom, method: :get, html: { class: 'form-inline' }  do |f| %>
          <div class="form-group">

            <%= f.input :price, label: false, placeholder: "maximum budget"  %>

          </div>
          <div class="form-group options">
            <div>
              <%= f.label :handicapped  %>
              <%= f.input_field :handicapped, as: :boolean %>
            </div>
            <div>

              <%= f.label :baby  %>
              <%= f.input_field :baby, as: :boolean %>
            </div>
            <div>
              <%= f.label :bidet %>
              <%= f.input_field :bidet, as: :boolean %>

            </div>
            <div>
              <%= f.label :wipes %>
              <%= f.input_field :wipes, as: :boolean %>

            </div>


          </div>
            <div class="form-group options">

              <div>
              <%= f.label :style %>
               <%= f.select :style, style: %w(western turkish japanese) %>

              <%= f.label :paper %>
               <%= f.select :toilet_paper, toilet_paper: [1,2,3,4,5] %>

            <%= f.submit "submit", class:"btn btn-primary submit" %>
             </div>
           </div>
        </div>


      <% end %>

    </div>
  </div>
  <card-container class="card-container">
    <div class="row">

      <% @bathrooms.each do |bathroom| %>

      <% string = Bathroom.class_string(bathroom) %>
      <div class="col-xs-12 col-md-6">

        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.6)0%, rgba(0,0,0,0.0)25%, rgba(0,0,0,0.2)75%, rgba(0,0,0,0.8)100%),url(<%= cl_image_path(bathroom.photo, height: 400, width: 400, crop: :fit) %>);" <%= string %>>
          <div class="card-category"><%= bathroom.price.fdiv(100) %>€</div>
          <div class="white-card-background"></div>
          <div class="card-description">
            <h2><%= bathroom.title %></h2>
            <p>
              <% average = bathroom.average %>
              <% average.to_i.times do %>
              <i class="fa fa-star"></i>
              <% end %>
              <% if (average - average.to_i) > 0.3  %>
              <i class="fa fa-star-half"></i>
              <% end %>
            </p>
          </div>

          <%= cl_image_tag(bathroom.user.photo, class: "card-user") %>

          <%= link_to "" ,bathroom_path(bathroom), class:"card-link" %>
          <!-- </div> -->
          <%= cl_image_tag(bathroom.user.photo, height: 400, width: 400, crop: :fit, class: "card-user") %>
        </div>
      </div>


      <% end %>
    </div>
  </card-container>

  <div
  id="map" class="map-container"
  style="min-width: 300px; width: 100%; height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-user_marker="<%= @user_marker.to_json %>"
  data-user_location="<%= @user_location.to_json %>">
</div>
</div>

<!-- might need styling, see _index.scss -->


</div>

</div>

app/views/bathrooms/new.html.erb
<div class="container new-bathroom-form"><h1>Host your toilet!</h1>
  <div>
    <%= simple_form_for @bathroom do |f| %>
      <%= f.input :title, placeholder: "Enter a Tagline" %>
      <%= f.input :address, placeholder: "Streetname and number" %>
      <%= f.input :plz, as: :integer%>
      <%= f.input :city %>
      <%= f.input :description, placeholder: "Further describe your bathroom", as: :text %>
      <%= f.input :style, collection: ["western", "turkish", "japanese"], required: false %>
      <%= f.input :price, placeholder: "in cents e.g 5€ = 500", as: :integer %>
      <%= f.input :handicapped, label: "Wheelchair accessible?", as: :boolean, required: false %>
      <%= f.input :toilet_paper, label: "How many plies does your toilet paper have?", collection: 1..5, required: false %>
      <%= f.input :wipes, label: "Wetwipes?", as: :boolean, required: false %>
      <%= f.input :baby, label: "Diaper-changing table?", as: :boolean, required: false %>
      <%= f.input :bidet, label: "Bidet?", as: :boolean, required: false %>
      <%= f.input :photo, label: "Upload a nice picture of your bathroom" %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit %>
      <% end %>
    <p>All fields marked with a * are required</p>
  </div>
</div>

app/views/bathrooms/show.html.erb
<div class="wrapper">

  <div class="container">
    <div class="show-bathroom">
      <div class="bathroom-info">
        <p class = "uptag"><%= @bathroom.style.upcase %> TOILET IN <%= @bathroom.city.upcase %> </p>
        <div class="bathroom-head">
          <div class="main-infos">
            <h1 class="title"><%= @bathroom.title %>  </h1>
            <h2><% @bathroom.average.to_i.times do %>
                <i class="fa fa-star"></i>
                <% end %>
              <% if (@bathroom.average - @bathroom.average.to_i) > 0.3  %>
                  <i class="fa fa-star-half"></i>
                <% end %>
              </h2>
          </div>
          <div class="avatar-container">
            <%= link_to "#" do   %>
            <%= cl_image_tag @owner.photo, height: 100, width: 100, crop: :fill, class: "avatar-bordered" %>
            <% end %>
          </div>
        </div>

        <div class="bathroom-properties">
          <i class="fas fa-align-justify"></i>

          <span><%= @bathroom.toilet_paper %>-ply paper</span>
          <span>
            <%  if @bathroom.handicapped %>
            <i class="fab fa-accessible-icon"></i>
            <span>Accessible</span>
            <% end %>
          </span>
          <span>

            <%  if @bathroom.baby %>
            <i class="fas fa-child"></i> <span>Babies welcome</span>
            <% end %>
          </span>

          <span>
            <%  if @bathroom.wipes %>
            <i class="far fa-sticky-note"></i><span>Wipes available</span>
            <% end %>
          </span>

          <span>
            <%  if @bathroom.bidet %>
            <i class="fas fa-bath"></i><span>Bidet available</span>
            <% end %>
          </span>

        </div>



        <div class="bathroom-description">

         <p><%= @bathroom.description %></p>

       </div>

       <%= link_to bathroom_bookings_path(@bathroom), method: :post do %>
       <button id="AJAXIFY THIS ON FRIDAY" class="btn btn-danger btn-lg btn-block">

        Book this bathroom for <%= @bathroom.price.to_f/100 %> €

      </button>

      <% end %>




    </div>


    <div class="bathroom-photo">
      <%= cl_image_tag @bathroom.photo, height: 600, width: 800, crop: :fill %>
      <!--         <%= link_to "See photos", "#", class: "photos-link btn btn-danger" %>-->    </div>

      <div
      id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-user_location="<%= @user_location.to_json %>"
      class="bathroom-map"
      >



    </div>
  </div>





<div class="container">

  <div class="review-box">
    <% @last_reviews.each do |review|%>
        <div class="review-field">
          <div class="review-user">
            <% if review.user%>
              <%= cl_image_tag(review.user.photo, class:"avatar review-avatar")%>
              <!-- <h2><%= review.user.first_name %> <%= review.user.last_name %></h2> -->
            <% end %>
          </div>
          <div class="review-details">
            <p> <%= review.content %> </p>
            <% review.rating.times do %>
              <i class="fa fa-star"></i>
            <% end %>
          </div>
        </div>
<% end %>
</div>

  <div class="review"><%= link_to "See All Reviews", bathroom_reviews_path(@bathroom) %></div>

</div>