config/routes.rb
Rails.application.routes.draw do

    namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bathrooms, only: [ :index ]
    end
  end

  put 'location_update', to: 'users#update_location', as: 'location_update'

 resources :bathrooms, only: [:new, :create, :show, :index] do
    resources :bookings, only: [:new, :create, :show, :index]
    resources :reviews, only: [:new, :create, :show, :index]
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :bathroom

  # validates :user, presence:true
  # validates :bathroom, presence:true

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @bathroom = Bathroom.find(params[:bathroom_id])
    @booking = Booking.new
    @booking.user = current_user
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user_id = current_user.id
    @booking.save
    redirect_to bathroom_booking_path(@booking.bathroom, @booking)
  end

  def index
    @bathroom = Bathroom.find(params[:bathroom_id])
    @bookings = policy_scope(Booking).where("bathroom_id = #{params[:bathroom_id]}")
  end

  def show
    require 'date'
    @booking = Booking.find(params[:id])
    @owner = @booking.bathroom.user
    @bathroom = @booking.bathroom
    @markers =
    [{
      lat: @bathroom.latitude,
      lng: @bathroom.longitude,
      icon: '/toilet-marker.png',
      draggable: false
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }]
    @user_location = session[:user_coordinates]
    # @user_marker = {
    #   lat: @user_location["latitude"],
    #   lng: @user_location["longitude"],
    #   icon: '/user-marker.png',
    #   draggable: true
    #   }
    authorize @booking
  end

  private

  # def get_booking

  # end

  # def get_bathroom

  # end

  def booking_params
    params.permit(:bathroom_id, :user)
  end
end

app/views/bookings/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addReview('<%= j render "reviews/show", review: @review %>');
  refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>

app/views/bookings/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1 class="text-center">Shit stats</h1>

    <div class="bookings-index">

      <div class="bookings-past">
<h2 class="text-center">Past bookings</h2>

        <ul>
          <% @bookings.select{|b| (Time.now - b.created_at) / 60 > 30 }.each do |booking| %>
          <li class= "listing">
            <%= cl_image_tag booking.user.photo, class: "avatar pic" %>


            <div class="listing-name">
                          <p>
              <strong>
            Visitor
              </strong>
          </p>
              <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
            </div>

            <div class="listing-time">


            <p>
              <strong>
            visit time
              </strong>
          </p>

          <p>
            <%= booking.created_at.strftime("%B %d at %H:%M") %>
          </p>
            </div>

            <div class="listing-status">

              <p>
                <strong>

              status
                </strong>
            </p>
            <p>
              job done
            </p>
            </div>

          </li>

          <% end %>
        </ul>

      </div>


      <div class="bookings-upcoming">

<h2 class="text-center">Upcoming bookings</h2>


        <ul>
          <% @bookings.select{|b| (Time.now - b.created_at) / 60 < 30 }.each do |booking| %>
          <li class= "listing">
            <%= cl_image_tag booking.user.photo, class: "avatar pic" %>


            <div class="listing-name">
                          <p>
              <strong>
            Visitor
              </strong>
          </p>
              <p><%= booking.user.first_name %> <%= booking.user.last_name %></p>
            </div>

            <div class="listing-time">


            <p>
              <strong>
            visit time
              </strong>
          </p>

          <p>
            <%= booking.created_at.strftime("%B %d at %H:%M") %>
          </p>
            </div>

            <div class="listing-status">

              <p>
                <strong>

              status
                </strong>
            </p>
            <p>
              on his way!
            </p>
            </div>

          </li>

          <% end %>
        </ul>

      </div>

      </div>


    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="wrapper">

  <div class="container">
    <div class="booking-grid">

      <div class="booking-info">


        <div class="run">
          <!-- <h1>Run!</h1> -->
        </div>

        <!-- <div class="where-info">
          <p>
            <%= @booking.bathroom.address %></p>
            <div class="user-info-vt">
              <p>
                Host: <%= @booking.bathroom.user.first_name %> <%= @booking.bathroom.user.last_name %>
              </p>
            </div>
          </div> -->

          <div class="text-time">
            <p>
              <strong>
                Time left for your booking:
              </strong>
            </p>

            <h4 id="booking-timer" data-created=<%= (@booking.created_at.to_f+30*60)*1000 %>></h4>
            <div class="clock-box">
              <div class="countdown-digital">
                <!-- MINUTE -->
                <div class="clock">
                  <div class="numbers">
                    <p class="minutes">00</p>
                    <p class="placeholder">88</p>
                  </div>

                  <div class="colon">
                    <p>:</p>
                  </div>

                  <!-- SECOND -->
                  <div class="numbers">
                    <p class="seconds">00</p>
                    <p class="placeholder">88</p>
                  </div>
                </div>
              </div>
            </div>
          </div>



          <div class="flush">
            <a href=<%= "#{new_bathroom_review_path}" %> class="btn btn-default flush-button" data-reviewpath=<%= new_bathroom_review_path %>>FLUSH</a>
          </div>



        </div>



        <div class="bathroom-info">
          <p class = "uptag"><%= @booking.bathroom.style.upcase %> TOILET IN <%= @booking.bathroom.city.upcase %> </p>
          <div class="bathroom-head">

            <div class="main-infos">
              <h1 class="title"><%= @booking.bathroom.title %></h1>
              <!-- <p class = "distance">600 m</p> -->
            </div>

          </div>

          <div class="bathroom-properties">
            <i class="fas fa-align-justify"></i>
            <span><%= @bathroom.toilet_paper %>-ply paper</span>
            <span>
              <%  if @bathroom.handicapped %>
              <i class="fab fa-accessible-icon"></i>
              <span>Accessible</span>
              <% end %>
            </span>
            <span>

              <%  if @bathroom.baby %>
              <i class="fas fa-child"></i> <span>Babies welcome</span>
              <% end %>
            </span>

            <span>
              <%  if @bathroom.wipes %>
              <i class="far fa-sticky-note"></i><span>Wipes available</span>
              <% end %>
            </span>

            <span>
              <%  if @bathroom.bidet %>
              <i class="fas fa-bath"></i><span>Bidet available</span>
              <% end %>
            </span>

          </div>

          <div class="bathroom-description">

           <p><%= @booking.bathroom.description %></p>

         </div>
       </div>


       <div
       id="map"
       style="width: 100%; height: 400px;"
       data-markers="<%= @markers.to_json %>"
       data-user_location="<%= @user_location.to_json %>"
       class="bathroom-map"
       >


     </div>
   </div>