config/routes.rb
Rails.application.routes.draw do

    namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bathrooms, only: [ :index ]
    end
  end

  put 'location_update', to: 'users#update_location', as: 'location_update'

 resources :bathrooms, only: [:new, :create, :show, :index] do
    resources :bookings, only: [:new, :create, :show, :index]
    resources :reviews, only: [:new, :create, :show, :index]
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#home'
  resources :users, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/home.html.erb
<%= render "shared/banner" %>

<script>
  if (window.navigator.geolocation) {
    var failure, success;
    success = function(position) {
      console.log(position);
      fetch("<%= location_update_path %>", {
        headers: { "Content-Type": "application/json" },
        credentials: 'same-origin',
        method: 'PUT',
        body: JSON.stringify({
          current_location: { latitude: position.coords.latitude, longitude: position.coords.longitude }
        })
          // send the position to controller method and store this params into session
        });
    }
    failure = function(message) {
      console.log(message);
      fetch("<%= location_update_path %>", {
        headers: { "Content-Type": "application/json" },
        credentials: 'same-origin',
        method: 'PUT',
        body: JSON.stringify({
          current_location: { latitude: 52.507278, longitude: 13.391548 }
        })
      });
    }
    navigator.geolocation.getCurrentPosition(success, failure, {
      maximumAge: Infinity,
      timeout: 5000
    });
  }
</script>